"""Reusable Tuya recordings library primitives."""

from .media import (
    CachedClipKey,
    MediaSyncStatus,
    cleanup_cached_media,
    parse_cached_media_name,
    safe_segment,
)
from .pion import create_webrtc_offer, read_helper_stderr, read_helper_stdout, start_pion_helper
from .ffmpeg import (
    extract_h264_thumbnail,
    extract_mp4_thumbnail,
    finalize_mp4_for_browser,
    finish_live_h264_remux,
    remux_h264_to_mp4,
    start_live_h264_remux,
)
from .ipc import (
    TuyaIpcPlaybackError,
    TuyaIpcRecordingBackend,
    drain_helper_events,
    pion_helper_path,
)
from .openapi import TuyaOpenApiAuthError, TuyaOpenApiClient, TuyaOpenApiError
from .recordings import (
    as_epoch_seconds,
    best_clip_match,
    clip_key,
    first_thumbnail_value,
    looks_like_thumbnail_key,
    merge_cached_clips,
    normalize_clip,
)
from .webrtc import (
    WebRTCProbeSummary,
    browser_relay_candidate_list,
    candidate_priority,
    filter_local_candidate_list,
    filter_webrtc_candidates,
    ice_servers,
    mqtt_message_body,
    mqtt_message_type,
    mqtt_session_id,
    normalize_outgoing_candidate,
    p2p_envelope,
    strip_sdp_candidates,
)

__all__ = [
    "CachedClipKey",
    "MediaSyncStatus",
    "cleanup_cached_media",
    "parse_cached_media_name",
    "safe_segment",
    "create_webrtc_offer",
    "read_helper_stderr",
    "read_helper_stdout",
    "start_pion_helper",
    "extract_h264_thumbnail",
    "extract_mp4_thumbnail",
    "finalize_mp4_for_browser",
    "finish_live_h264_remux",
    "remux_h264_to_mp4",
    "start_live_h264_remux",
    "TuyaIpcPlaybackError",
    "TuyaIpcRecordingBackend",
    "TuyaOpenApiAuthError",
    "TuyaOpenApiClient",
    "TuyaOpenApiError",
    "drain_helper_events",
    "pion_helper_path",
    "as_epoch_seconds",
    "best_clip_match",
    "clip_key",
    "first_thumbnail_value",
    "looks_like_thumbnail_key",
    "merge_cached_clips",
    "normalize_clip",
    "WebRTCProbeSummary",
    "browser_relay_candidate_list",
    "candidate_priority",
    "filter_local_candidate_list",
    "filter_webrtc_candidates",
    "ice_servers",
    "mqtt_message_body",
    "mqtt_message_type",
    "mqtt_session_id",
    "normalize_outgoing_candidate",
    "p2p_envelope",
    "strip_sdp_candidates",
]
